# Generated by Django 4.0.6 on 2023-01-30 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bizType', models.IntegerField(verbose_name='业务类型')),
                ('subNo', models.IntegerField(verbose_name='子编码')),
                ('dictName', models.CharField(max_length=100, verbose_name='枚举值')),
                ('remarks', models.CharField(max_length=255, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('spuId', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='商品SPU编码')),
                ('goodsName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsSpec',
            fields=[
                ('skuId', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='商品SKU编码')),
                ('upc', models.CharField(max_length=50, verbose_name='国条')),
                ('specName', models.CharField(max_length=255, verbose_name='规格名称')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.goods', verbose_name='商品')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptBill',
            fields=[
                ('receiptBillNo', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='收货单号')),
                ('source', models.CharField(max_length=200, verbose_name='单据来源')),
                ('sourceBillNo', models.CharField(max_length=200, verbose_name='来源单号')),
                ('stauts', models.CharField(max_length=200, verbose_name='状态')),
                ('creator', models.CharField(max_length=100, verbose_name='创建人')),
            ],
        ),
        migrations.CreateModel(
            name='SellOrder',
            fields=[
                ('soNo', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='销售单号')),
                ('soSn', models.IntegerField(verbose_name='订单序号')),
                ('totalAmount', models.IntegerField(verbose_name='订单总金额（分）')),
                ('totalGoodsAmount', models.IntegerField(verbose_name='商品原总价')),
                ('realPayTotal', models.IntegerField(verbose_name='订单实收金额（分）')),
                ('realMerTotal', models.IntegerField(verbose_name='商家实收金额（分）')),
                ('deliveryFee', models.IntegerField(verbose_name='配送费（分）')),
                ('lunchboxFee', models.IntegerField(verbose_name='餐盒费（分）')),
                ('platformServiceFee', models.IntegerField(verbose_name='平台服务费（分）')),
                ('merActFee', models.IntegerField(verbose_name='商家活动支出（分）')),
                ('platformActFee', models.IntegerField(verbose_name='平台活动支出（分）')),
                ('status', models.CharField(max_length=50, verbose_name='订单状态')),
                ('deliveryStatus', models.CharField(max_length=50, verbose_name='配送状态')),
                ('createTime', models.DateTimeField(verbose_name='下单时间')),
                ('finishTime', models.CharField(max_length=50, verbose_name='完成时间')),
                ('refundTime', models.CharField(max_length=50, verbose_name='订单取消时间')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('storeNo', models.IntegerField(primary_key=True, serialize=False, verbose_name='门店号')),
                ('storeName', models.CharField(max_length=20)),
                ('storeAddress', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='门店地址')),
            ],
        ),
        migrations.CreateModel(
            name='StoreGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retailPrice', models.IntegerField()),
                ('status', models.SmallIntegerField(default=0)),
                ('infoCreateTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('infoUpdateTime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.goodsspec', verbose_name='sku')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.store', verbose_name='门店')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplierNo', models.IntegerField(primary_key=True, serialize=False, verbose_name='供商编码')),
                ('supplierName', models.CharField(max_length=100, verbose_name='供商名称')),
                ('deliveryDays', models.IntegerField(default=100, verbose_name='到货时间')),
                ('paymentByDays', models.IntegerField(null=True, verbose_name='账期天数')),
            ],
        ),
        migrations.CreateModel(
            name='Bom',
            fields=[
                ('storeGoods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='主商品', serialize=False, to='core.storegoods', verbose_name='商品')),
                ('usage', models.FloatField(verbose_name='组件用量')),
            ],
        ),
        migrations.CreateModel(
            name='supplierSoBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billNo', models.CharField(max_length=100, verbose_name='单据号')),
                ('status', models.IntegerField(verbose_name='状态编码')),
                ('billTotalAmount', models.IntegerField(verbose_name='单据总价')),
                ('bizDate', models.DateField(verbose_name='单据日期')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.supplier', verbose_name='供商')),
            ],
        ),
        migrations.CreateModel(
            name='SoDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upc', models.CharField(max_length=100, verbose_name='UPC')),
                ('specName', models.CharField(max_length=100, verbose_name='规格名称')),
                ('unitName', models.CharField(max_length=100, verbose_name='单位名称')),
                ('qty', models.FloatField(verbose_name='销售数量')),
                ('isRefundGoods', models.CharField(max_length=100, verbose_name='是否为退款商品')),
                ('refundQty', models.FloatField(verbose_name='退货数量')),
                ('netQty', models.FloatField(verbose_name='净数量')),
                ('sellGoodsPrice', models.IntegerField(verbose_name='商品原销售单价（分）')),
                ('goodsSellAmount', models.IntegerField(verbose_name='原售价销售额小计(分)')),
                ('goodsRealPayAmount', models.IntegerField(verbose_name='商品实付金额（分）')),
                ('goodsRefundAmount', models.IntegerField(verbose_name='退款商品金额（分）')),
                ('goodsPerkTotalAmount', models.IntegerField(verbose_name='商品总补贴金额（分）')),
                ('goodsPerkMerAmount', models.IntegerField(verbose_name='商品商家补贴金额 (分)')),
                ('goodsPerkPlatformAmount', models.IntegerField(verbose_name='商品平台补贴金额 (分)')),
                ('refundTime', models.CharField(max_length=100, verbose_name='退款时间')),
                ('refSo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sellorder', verbose_name='所属销售订单号')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.goodsspec', verbose_name='sku')),
            ],
        ),
        migrations.AddField(
            model_name='sellorder',
            name='store',
            field=models.ForeignKey(default=1031328, on_delete=django.db.models.deletion.PROTECT, to='core.store', verbose_name='门店'),
        ),
        migrations.CreateModel(
            name='ReceiptBillItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=100, verbose_name='发货单位')),
                ('sendQty', models.FloatField(default=0, verbose_name='发货量')),
                ('netRecQty', models.FloatField(default=0, verbose_name='净收货量')),
                ('recQty', models.FloatField(default=0, verbose_name='收货量')),
                ('grandTotalRefund', models.FloatField(default=0, verbose_name='累计退货量')),
                ('offset', models.FloatField(default=0, verbose_name='偏差量')),
                ('actPurchasePrice', models.IntegerField(default=0, verbose_name='当前可用采购价（分）')),
                ('purchasePriceByBill', models.IntegerField(default=0, verbose_name='单据记录的采购价（分）')),
                ('purchaseAmount', models.IntegerField(default=0, verbose_name='采购总价')),
                ('netPurchaseAmount', models.IntegerField(default=0, verbose_name='净收货总价')),
                ('receiver', models.CharField(default='收货人为空', max_length=100, verbose_name='收货人')),
                ('receiveTime', models.CharField(blank=True, max_length=100, null=True, verbose_name='收货时间')),
                ('receiptBill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.receiptbill', verbose_name='收货单')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.goodsspec', verbose_name='SKU')),
            ],
        ),
        migrations.AddField(
            model_name='receiptbill',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.store', verbose_name='门店'),
        ),
        migrations.AddField(
            model_name='receiptbill',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.supplier', verbose_name='供商'),
        ),
        migrations.CreateModel(
            name='PurchaseRelations',
            fields=[
                ('relationNo', models.IntegerField(primary_key=True, serialize=False, verbose_name='供货关系编码')),
                ('arrivalDays', models.IntegerField(null=True, verbose_name='到货天数')),
                ('purUnit', models.CharField(max_length=50, null=True, verbose_name='采购单位')),
                ('isDefault', models.CharField(max_length=50, null=True, verbose_name='是否默认')),
                ('purPrice', models.IntegerField(verbose_name='采购价（分）')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.goodsspec', verbose_name='SKU')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.store', verbose_name='门店')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.supplier', verbose_name='供商')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('poNo', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='销售单号')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.store', verbose_name='门店')),
            ],
        ),
        migrations.CreateModel(
            name='poPayBillItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payAmount', models.IntegerField(verbose_name='支付金额（分）')),
                ('payChannel', models.IntegerField(verbose_name='支付渠道')),
                ('payTime', models.DateTimeField(verbose_name='支付时间')),
                ('refReceiptBill', models.ManyToManyField(to='core.receiptbill', verbose_name='关联收货单号')),
            ],
        ),
        migrations.CreateModel(
            name='poPayBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payAmount', models.IntegerField(verbose_name='支付金额（分）')),
                ('payChannel', models.IntegerField(verbose_name='支付渠道')),
                ('payTime', models.DateTimeField(verbose_name='支付时间')),
                ('refReceiptBill', models.ManyToManyField(to='core.receiptbill', verbose_name='关联收货单号')),
            ],
        ),
        migrations.CreateModel(
            name='checkBillDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellOrder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sellorder', verbose_name='销售单')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billNo', models.CharField(max_length=100, verbose_name='单据号')),
                ('createTime', models.CharField(max_length=100, verbose_name='单据创建时间')),
                ('status', models.CharField(max_length=100, verbose_name='单据状态')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.store', verbose_name='门店')),
            ],
        ),
        migrations.AddConstraint(
            model_name='storegoods',
            constraint=models.UniqueConstraint(fields=('store', 'sku'), name='门店+商品不重复'),
        ),
        migrations.AddConstraint(
            model_name='sodetails',
            constraint=models.UniqueConstraint(fields=('refSo', 'sku', 'qty', 'goodsPerkTotalAmount', 'refundQty'), name='订单号+商品+数量不重复'),
        ),
        migrations.AddConstraint(
            model_name='receiptbillitems',
            constraint=models.UniqueConstraint(fields=('receiptBill', 'sku', 'receiveTime'), name='收货单+商品不重复'),
        ),
        migrations.AddConstraint(
            model_name='purchaserelations',
            constraint=models.UniqueConstraint(fields=('store', 'sku', 'supplier', 'purPrice'), name='店、品、供商、采购价联合唯一'),
        ),
        migrations.AddField(
            model_name='bom',
            name='unitGoods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='子商品', to='core.storegoods', verbose_name='子商品'),
        ),
    ]
