# Generated by Django 4.0.6 on 2023-01-27 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('spuId', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='商品SPU编码')),
                ('goodsName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skuId', models.BigIntegerField(unique=True, verbose_name='商品SKU编码')),
                ('upc', models.CharField(max_length=50, verbose_name='国条')),
                ('specName', models.CharField(max_length=255, verbose_name='规格名称')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.goods', verbose_name='商品')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poNo', models.CharField(max_length=50, unique=True, verbose_name='销售单号')),
                ('purPrice', models.BigIntegerField(verbose_name='本次采购价')),
                ('realMerTotal', models.IntegerField(verbose_name='商家实收金额')),
            ],
        ),
        migrations.CreateModel(
            name='SellOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soNo', models.CharField(max_length=50, unique=True, verbose_name='销售单号')),
                ('status', models.SmallIntegerField(verbose_name='订单状态码')),
                ('createTime', models.DateTimeField(verbose_name='下单时间')),
                ('finishTime', models.DateTimeField(verbose_name='完成时间')),
                ('totalAmount', models.IntegerField(verbose_name='销售额（分）')),
                ('realPayTotal', models.IntegerField(verbose_name='顾客实付金额（分）')),
                ('realMerTotal', models.IntegerField(verbose_name='商家实收（分）')),
                ('deliveryFee', models.IntegerField(verbose_name='配送费（分）')),
                ('lunchboxFee', models.IntegerField(verbose_name='餐盒费（分）')),
                ('mtServiceFee', models.IntegerField(verbose_name='(美团)平台服务费（分）')),
                ('merActFee', models.IntegerField(verbose_name='商家活动支出（分）')),
                ('mtActFee', models.IntegerField(verbose_name='平台活动支出（分）')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeType', models.SmallIntegerField(default='0')),
                ('storeNo', models.IntegerField(unique=True)),
                ('storeName', models.CharField(max_length=20)),
                ('storeAddress', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='门店地址')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplierNo', models.IntegerField(unique=True, verbose_name='供商编码')),
                ('supplierName', models.CharField(max_length=20, verbose_name='供商名称')),
                ('deliveryDays', models.IntegerField(default=100, verbose_name='到货时间')),
                ('paymentByDays', models.IntegerField(verbose_name='账期天数')),
                ('starValue', models.IntegerField(verbose_name='供商分值')),
            ],
        ),
        migrations.CreateModel(
            name='StoreGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retailPrice', models.IntegerField()),
                ('status', models.SmallIntegerField(default=0)),
                ('infoCreateTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('infoUpdateTime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.goodsspec', to_field='skuId', verbose_name='sku')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.store', to_field='storeNo', verbose_name='门店')),
            ],
        ),
        migrations.CreateModel(
            name='SoDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField(verbose_name='销售数量')),
                ('refundQty', models.FloatField(verbose_name='退货数量')),
                ('netQty', models.FloatField(verbose_name='净数量')),
                ('sellPrice', models.FloatField(verbose_name='原售价')),
                ('cost', models.FloatField(verbose_name='成本价')),
                ('purPrice', models.FloatField(verbose_name='下单时采购价')),
                ('refSo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sellorder', to_field='soNo', verbose_name='所属销售订单号')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.storegoods', verbose_name='sku')),
            ],
        ),
        migrations.CreateModel(
            name='ReciptBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sysCode', models.SmallIntegerField(default='mtsg', verbose_name='系统编号')),
                ('reciptBillNo', models.CharField(max_length=50, verbose_name='收货单号')),
                ('sendQty', models.FloatField(default=0, verbose_name='发货量')),
                ('netRecQty', models.FloatField(default=0, verbose_name='净收货量')),
                ('recQty', models.FloatField(default=0, verbose_name='收货量')),
                ('grandTotalRefund', models.FloatField(default=0, verbose_name='累计退货量')),
                ('offset', models.FloatField(default=0, verbose_name='偏差量')),
                ('purchasePrice', models.IntegerField(default=0, verbose_name='采购价（分）')),
                ('purchasePriceByBill', models.IntegerField(default=0, verbose_name='单据记录的采购价（分）')),
                ('purchaseAmount', models.IntegerField(default=0, verbose_name='采购总价')),
                ('netPurchaseAmount', models.IntegerField(default=0, verbose_name='净收货总价')),
                ('receiver', models.CharField(default='收货人为空', max_length=100, verbose_name='收货人')),
                ('receiveTime', models.DateTimeField(blank=True, null=True, verbose_name='收货时间')),
                ('refPurBill', models.ForeignKey(default='0', on_delete=django.db.models.deletion.PROTECT, to='core.purchaseorder', to_field='poNo', verbose_name='参考采购单')),
                ('sender', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='core.supplier', to_field='supplierNo', verbose_name='发货方')),
                ('shop', models.ForeignKey(default=15307602, on_delete=django.db.models.deletion.PROTECT, to='core.store', to_field='storeNo', verbose_name='门店')),
                ('storeGoods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.storegoods', verbose_name='商品')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRelations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationNo', models.IntegerField(verbose_name='供化关系编码')),
                ('arrivalDays', models.IntegerField(verbose_name='到货天数')),
                ('purUnit', models.CharField(max_length=50, verbose_name='采购单位')),
                ('isDefault', models.CharField(max_length=50, verbose_name='是否默认')),
                ('purPrice', models.IntegerField(verbose_name='采购价（分）')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.goodsspec', to_field='skuId', verbose_name='SKU')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.store', to_field='storeNo', verbose_name='门店')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.supplier', to_field='supplierNo', verbose_name='供商')),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.store', to_field='storeNo', verbose_name='门店'),
        ),
        migrations.CreateModel(
            name='checkBillDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellOrder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sellorder', to_field='soNo', verbose_name='销售单')),
            ],
        ),
        migrations.CreateModel(
            name='Bom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage', models.FloatField(verbose_name='组件用量')),
                ('storeGoods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='主商品', to='core.storegoods', verbose_name='商品')),
                ('unitGoods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='子商品', to='core.storegoods', verbose_name='子商品')),
            ],
        ),
        migrations.AddConstraint(
            model_name='storegoods',
            constraint=models.UniqueConstraint(fields=('store', 'sku'), name='门店+商品不重复'),
        ),
        migrations.AddConstraint(
            model_name='sodetails',
            constraint=models.UniqueConstraint(fields=('refSo', 'sku', 'qty', 'refundQty'), name='订单号+商品+数量不重复'),
        ),
    ]
