# Generated by Django 4.0.6 on 2023-01-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='paymentByDays',
            field=models.IntegerField(null=True, verbose_name='账期天数'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='starValue',
            field=models.IntegerField(null=True, verbose_name='供商分值'),
        ),
    ]
