# Generated by Django 4.0.6 on 2023-01-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_by_day', models.DateField(verbose_name='日期')),
                ('goods_name', models.CharField(max_length=100, verbose_name='商品名称')),
                ('sku_id', models.CharField(max_length=100, verbose_name='商品SKU')),
                ('hours_on_show', models.IntegerField(verbose_name='在售时长')),
                ('volume', models.IntegerField(verbose_name='销量')),
            ],
        ),
    ]
