# Generated by Django 4.0.6 on 2023-01-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_supplier_paymentbydays_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplierName',
            field=models.CharField(max_length=100, verbose_name='供商名称'),
        ),
    ]
