# Generated by Django 4.0.6 on 2023-01-27 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_goodsspec_skuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaserelations',
            old_name='sku',
            new_name='skuId',
        ),
    ]
