# Generated by Django 4.0.6 on 2023-01-27 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_sku_purchaserelations_skuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaserelations',
            old_name='skuId',
            new_name='sku',
        ),
    ]
