# Generated by Django 4.0.6 on 2023-01-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_skuid_purchaserelations_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserelations',
            name='arrivalDays',
            field=models.IntegerField(null=True, verbose_name='到货天数'),
        ),
        migrations.AlterField(
            model_name='purchaserelations',
            name='isDefault',
            field=models.CharField(max_length=50, null=True, verbose_name='是否默认'),
        ),
        migrations.AlterField(
            model_name='purchaserelations',
            name='purUnit',
            field=models.CharField(max_length=50, null=True, verbose_name='采购单位'),
        ),
    ]
