# Generated by Django 4.0.6 on 2023-01-27 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_purchaserelations_arrivaldays_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReciptBill',
            new_name='ReciptBillItems',
        ),
    ]
