# Generated by Django 4.0.6 on 2023-01-27 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_dictionary_rename_shop_reciptbillitems_store_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReciptBillItems',
        ),
    ]
