# Generated by Django 4.0.6 on 2023-01-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_reciptbillitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciptbillitems',
            name='receiveTime',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='收货时间'),
        ),
    ]
