# Generated by Django 4.0.6 on 2023-01-27 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_reciptbillitems_receivetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reciptbillitems',
            name='reciptBill',
        ),
        migrations.RemoveField(
            model_name='reciptbillitems',
            name='sku',
        ),
        migrations.DeleteModel(
            name='ReciptBill',
        ),
        migrations.DeleteModel(
            name='ReciptBillItems',
        ),
    ]
