# Generated by Django 4.0.6 on 2023-01-28 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_reciptbill_reciptbillitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='supplierSoBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billNo', models.CharField(max_length=100, verbose_name='单据号')),
                ('status', models.IntegerField(verbose_name='状态编码')),
                ('billTotalAmount', models.IntegerField(verbose_name='单据总价')),
                ('bizDate', models.DateField(verbose_name='单据日期')),
            ],
        ),
        migrations.AddConstraint(
            model_name='reciptbillitems',
            constraint=models.UniqueConstraint(fields=('reciptBill', 'sku', 'receiveTime'), name='收货单+商品不重复'),
        ),
        migrations.AddField(
            model_name='suppliersobill',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.supplier', to_field='supplierNo', verbose_name='供商'),
        ),
    ]
