# Generated by Django 4.0.6 on 2023-01-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_suppliersobill_reciptbillitems_收货单+商品不重复_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='poPayBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payAmount', models.IntegerField(verbose_name='支付金额（分）')),
                ('payChannel', models.IntegerField(verbose_name='支付渠道')),
                ('payTime', models.DateTimeField(verbose_name='支付时间')),
                ('refReciptBill', models.ManyToManyField(to='core.reciptbill', verbose_name='关联收货单号')),
            ],
        ),
    ]
