# Generated by Django 4.0.6 on 2023-01-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_sellorder_status_popaybillitems_popaybill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellorder',
            name='finishTime',
            field=models.CharField(max_length=50, verbose_name='完成时间'),
        ),
    ]
