# Generated by Django 4.0.6 on 2023-01-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_sellorder_finishtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellorder',
            old_name='mtActFee',
            new_name='platformActFee',
        ),
        migrations.RemoveField(
            model_name='sellorder',
            name='mtServiceFee',
        ),
        migrations.AddField(
            model_name='sellorder',
            name='deliveryStatus',
            field=models.CharField(default=0, max_length=50, verbose_name='配送状态'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellorder',
            name='platformServiceFee',
            field=models.IntegerField(default=0, verbose_name='平台服务费（分）'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellorder',
            name='refundTime',
            field=models.CharField(default=0, max_length=50, verbose_name='订单取消时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellorder',
            name='totalGoodsAmount',
            field=models.IntegerField(default=0, verbose_name='商品原总价'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sodetails',
            name='soType',
            field=models.CharField(default=0, max_length=50, verbose_name='订单类型'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellorder',
            name='realMerTotal',
            field=models.IntegerField(verbose_name='商家实收金额（分）'),
        ),
        migrations.AlterField(
            model_name='sellorder',
            name='realPayTotal',
            field=models.IntegerField(verbose_name='订单实收金额（分）'),
        ),
        migrations.AlterField(
            model_name='sellorder',
            name='totalAmount',
            field=models.IntegerField(verbose_name='订单总金额（分）'),
        ),
    ]
