# Generated by Django 4.0.6 on 2023-01-29 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_mtactfee_sellorder_platformactfee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sodetails',
            name='refSo',
        ),
        migrations.RemoveField(
            model_name='sodetails',
            name='sku',
        ),
        migrations.DeleteModel(
            name='checkBillDetails',
        ),
        migrations.DeleteModel(
            name='SellOrder',
        ),
        migrations.DeleteModel(
            name='SoDetails',
        ),
    ]
