# Generated by Django 4.0.6 on 2023-01-29 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_sodetails_refso_remove_sodetails_sku_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soNo', models.CharField(max_length=50, unique=True, verbose_name='销售单号')),
                ('totalAmount', models.IntegerField(verbose_name='订单总金额（分）')),
                ('totalGoodsAmount', models.IntegerField(verbose_name='商品原总价')),
                ('realPayTotal', models.IntegerField(verbose_name='订单实收金额（分）')),
                ('realMerTotal', models.IntegerField(verbose_name='商家实收金额（分）')),
                ('deliveryFee', models.IntegerField(verbose_name='配送费（分）')),
                ('lunchboxFee', models.IntegerField(verbose_name='餐盒费（分）')),
                ('platformServiceFee', models.IntegerField(verbose_name='平台服务费（分）')),
                ('merActFee', models.IntegerField(verbose_name='商家活动支出（分）')),
                ('platformActFee', models.IntegerField(verbose_name='平台活动支出（分）')),
                ('status', models.CharField(max_length=50, verbose_name='订单状态')),
                ('deliveryStatus', models.CharField(max_length=50, verbose_name='配送状态')),
                ('createTime', models.DateTimeField(verbose_name='下单时间')),
                ('finishTime', models.CharField(max_length=50, verbose_name='完成时间')),
                ('refundTime', models.CharField(max_length=50, verbose_name='订单取消时间')),
            ],
        ),
        migrations.CreateModel(
            name='SoDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soType', models.CharField(max_length=50, verbose_name='订单类型')),
                ('qty', models.FloatField(verbose_name='销售数量')),
                ('refundQty', models.FloatField(verbose_name='退货数量')),
                ('netQty', models.FloatField(verbose_name='净数量')),
                ('sellPrice', models.FloatField(verbose_name='原售价')),
                ('cost', models.FloatField(verbose_name='成本价')),
                ('purPrice', models.FloatField(verbose_name='下单时采购价')),
                ('refSo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sellorder', to_field='soNo', verbose_name='所属销售订单号')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.storegoods', verbose_name='sku')),
            ],
        ),
        migrations.CreateModel(
            name='checkBillDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellOrder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sellorder', to_field='soNo', verbose_name='销售单')),
            ],
        ),
        migrations.AddConstraint(
            model_name='sodetails',
            constraint=models.UniqueConstraint(fields=('refSo', 'sku', 'qty', 'refundQty'), name='订单号+商品+数量不重复'),
        ),
    ]
