# Generated by Django 4.0.6 on 2023-01-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_sellorder_sodetails_checkbilldetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellorder',
            name='soSn',
            field=models.IntegerField(default=0, verbose_name='订单序号'),
            preserve_default=False,
        ),
    ]
